In [6]:
import pandas as pd
import numpy as np
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score,roc_curve,auc

In [2]:
df = pd.read_excel('./8_appendicitis_exp3/2class/prob.xlsx')

In [3]:
df

ori_GT  ori_pred  ori_0_prob   ori_1_prob   Unnamed: 4  rgb_GT  \
0          0         0    0.999999  1.444389e-06         NaN       0   
1          0         0    0.858961  1.410390e-01         NaN       0   
2          0         0    0.891431  1.085690e-01         NaN       0   
3          0         1    0.021245  9.787552e-01         NaN       0   
4          0         0    1.000000  3.671940e-07         NaN       0   
...      ...       ...         ...           ...         ...     ...   
2777       1         0    1.000000  5.121912e-11         NaN       1   
2778       1         0    0.999999  1.259833e-06         NaN       1   
2779       1         0    1.000000  1.083859e-09         NaN       1   
2780       1         0    0.999987  1.301696e-05         NaN       1   
2781       1         0    1.000000  1.415962e-10         NaN       1   

      rgb_pred  rgb_0_prob   rgb_1_prob   
0            0    1.000000  6.441744e-10  
1            0    0.998768  1.232528e-03  
2            0    1.000000  4.874440e-07  
3            0    0.999704  2.956139e-04  
4            0    1.000000  2.800950e-11  
...        ...         ...           ...  
2777         0    0.999889  1.109597e-04  
2778         0    0.999990  1.005670e-05  
2779         0    1.000000  5.647795e-09  
2780         0    1.000000  1.934312e-07  
2781         0    1.000000  2.523408e-13  

[2782 rows x 9 columns]

In [4]:
ori_gt = df['ori_GT'].tolist()
ori_pred = df['ori_pred'].tolist()

In [10]:
cm=confusion_matrix(ori_gt,ori_pred)
print(cm)
print(cm.ravel())
tp,fn,fp,tn=cm.ravel()

print(tp,fn,fp,tn)
acc=accuracy_score(ori_gt,ori_pred)
sensitivity=tp/(tp+fn)
specificity=tn/(tn+fp)
precision=tp/(tp+fp)
recall=tp/(tp+fn)
F1_score=2*precision*recall/(precision+recall)

print(acc)
print(sensitivity)
print(specificity)
print(precision)
print(recall)
print(F1_score)

[[1845  114]
 [ 232  591]]
[1845  114  232  591]
1845 114 232 591
0.875629043853343
0.9418070444104135
0.7181044957472661
0.8883004333172846
0.9418070444104135
0.9142715559960357


In [13]:
rgb_gt = df['rgb_GT'].tolist()
rgb_pred = df['rgb_pred'].tolist()
cm=confusion_matrix(rgb_gt,rgb_pred)
print(cm)
print(cm.ravel())
tp,fn,fp,tn=cm.ravel()

print(tp,fn,fp,tn)
acc=accuracy_score(rgb_gt,rgb_pred)
sensitivity=tp/(tp+fn)
specificity=tn/(tn+fp)
precision=tp/(tp+fp)
recall=tp/(tp+fn)
F1_score=2*precision*recall/(precision+recall)

print(acc)
print(sensitivity)
print(specificity)
print(precision)
print(recall)
print(F1_score)

[[1856  103]
 [ 195  628]]
[1856  103  195  628]
1856 103 195 628
0.892882818116463
0.9474221541602859
0.7630619684082625
0.9049244271087274
0.9474221541602859
0.9256857855361597
